# Generated by Django 6.0.3 on 2026-03-12 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('profession', models.CharField(blank=True, max_length=150, verbose_name='Profession')),
                ('id_document', models.FileField(blank=True, null=True, upload_to='tenants/id_documents/', verbose_name="Pièce d'identité")),
                ('guarantor_name', models.CharField(blank=True, max_length=200, verbose_name='Nom du garant')),
                ('guarantor_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone du garant')),
                ('guarantor_document', models.FileField(blank=True, null=True, upload_to='tenants/guarantors/', verbose_name='Document garant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Locataire',
                'verbose_name_plural': 'Locataires',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name="Date d'entrée")),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de sortie')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Loyer HC (FCFA)')),
                ('charges', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Charges (FCFA)')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Dépôt de garantie (FCFA)')),
                ('annual_revision_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux de révision annuelle (%)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('active', 'Actif'), ('terminated', 'Résilié')], default='pending', max_length=10, verbose_name='Statut')),
                ('signed_contract', models.FileField(blank=True, null=True, upload_to='leases/contracts/', verbose_name='Contrat signé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='properties.property')),
            ],
            options={
                'verbose_name': 'Bail',
                'verbose_name_plural': 'Baux',
                'ordering': ['-start_date'],
            },
        ),
    ]
