# Generated by Django 6.0.3 on 2026-03-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('receipt', 'Quittance de loyer'), ('lease', 'Contrat de bail'), ('certificate', 'Attestation')], max_length=15, verbose_name='Type de document')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Fichier')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Généré le')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('unpaid', 'Loyer impayé'), ('lease_end', 'Fin de bail proche'), ('revision', 'Révision de loyer'), ('document_ready', 'Document disponible')], max_length=20, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
