# Generated by Django 6.0.3 on 2026-03-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='Action')),
                ('model_name', models.CharField(max_length=100, verbose_name='Modèle')),
                ('object_id', models.CharField(max_length=50, verbose_name='ID objet')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='Ancienne valeur')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='Nouvelle valeur')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('works', 'Travaux'), ('tax', 'Taxe / Impôt'), ('agency_fee', "Frais d'agence"), ('co_ownership', 'Copropriété'), ('other', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('invoice', models.FileField(blank=True, null=True, upload_to='accounting/invoices/', verbose_name='Facture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('late', 'En retard'), ('partial', 'Partiel')], default='pending', max_length=10, verbose_name='Statut')),
                ('method', models.CharField(blank=True, choices=[('cash', 'Espèces'), ('bank_transfer', 'Virement bancaire'), ('check', 'Chèque'), ('mobile_money', 'Mobile Money')], max_length=20, verbose_name='Méthode de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-due_date'],
            },
        ),
    ]
