# Generated by Django 6.0.3 on 2026-03-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Nom icône (ex: home, building)', max_length=50)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Équipement')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/')),
                ('is_main', models.BooleanField(default=False, verbose_name='Photo principale')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Type de bien',
                'verbose_name_plural': 'Types de biens',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=200, verbose_name="Nom de l'acheteur")),
                ('buyer_email', models.EmailField(blank=True, max_length=254)),
                ('buyer_phone', models.CharField(blank=True, max_length=20)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Prix de vente (FCFA)')),
                ('sale_date', models.DateField(blank=True, null=True, verbose_name='Date de vente')),
                ('notary_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Frais de notaire (FCFA)')),
                ('status', models.CharField(choices=[('pending', 'En cours'), ('signed', 'Signé'), ('cancelled', 'Annulé')], default='pending', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('surface', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Surface (m²)')),
                ('rooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Pièces')),
                ('listing_type', models.CharField(choices=[('rent', 'Location'), ('sale', 'Vente'), ('both', 'Location & Vente')], default='rent', max_length=10, verbose_name="Type d'annonce")),
                ('rent_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Loyer HC (FCFA)')),
                ('charges', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Charges (FCFA)')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Prix de vente (FCFA)')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('rented', 'Loué'), ('sold', 'Vendu'), ('under_construction', 'En travaux'), ('reserved', 'Réservé')], default='available', max_length=20, verbose_name='Statut')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipments', models.ManyToManyField(blank=True, related_name='properties', to='properties.equipment')),
            ],
            options={
                'verbose_name': 'Bien immobilier',
                'verbose_name_plural': 'Biens immobiliers',
                'ordering': ['-created_at'],
            },
        ),
    ]
